### ISSUE TITLE
update_folder returns "version-mismatch"

### ISSUE THREAD

**Issue by mbovo** [m0nhawk/grafana_api#29]
**What API call you use?**
`grafana_api.folder.update_folder(id, "title"):`

**What is the actual output?**
`Client Error 412: {"message":"The folder has been changed by someone else","status":"version-mismatch"}`

**What is the expected output?**
The api should change the folder title and potentially ask for overwrite or folder version
(see: https://grafana.com/docs/http_api/folder/#update-folder)

**Comment by m0nhawk** [comment]
Thank you for the Pull Requet. I have reviewed and released a new version.
