### ISSUE TITLE
Timeout for snapshot

### ISSUE THREAD

**Issue by nemaniaparna** [m0nhawk/grafana_api#47]
Is there any "timeout" option , when creating snapshot using HTTP API, not only via grafana GUI. Because when there are complex queries to execute on background, query is failing without timeout option.

Thanks in advance.

**Comment by m0nhawk** [comment]
The `timeout` option is available for [`GrafanaFace`](https://github.com/m0nhawk/grafana_api/blob/135d7c7acdd7dd48614603c4b371acc0658aef65/grafana_api/grafana_face.py#L27) like that:

```
gapi = GrafanaFace(auth=('admin', 'admin'), host='localhost', port=3000, timeout=30)
```

Let me know if this answers your question.

**Comment by nemaniaparna** [comment]
No it isn't working like that. 

grafana = SnapshotFace(auth=api, host='XXXX', port='443', protocol='https', timeout=30)
TypeError: __init__() got an unexpected keyword argument 'timeout'
: __init__() got an unexpected keyword argument 'timeout

**Comment by m0nhawk** [comment]
And version of `grafana_api` are you using? This was introduced in `0.8.5`, so any version after that should work.

**Comment by taubsix3** [comment]
i need an example for create and update dashboard, where i can find the values?
