### ISSUE TITLE
Module import fails for v0.3.1

### ISSUE THREAD

**Issue by svet-b** [m0nhawk/grafana_api#5]
Firstly, thanks for a very useful package! The new refactoring of the module structure also looks like a good step forward.

However, the module bundled in the latest package (v0.3.1) cannot actually be imported:
```
>>> import grafana_api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/grafana_api-0.3.1-py3.6.egg/grafana_api/__init__.py", line 1, in <module>
    from .grafana_face import GrafanaFace
  File "/usr/local/lib/python3.6/site-packages/grafana_api-0.3.1-py3.6.egg/grafana_api/grafana_face.py", line 2, in <module>
    from .api import Base
ModuleNotFoundError: No module named 'grafana_api.api'
```

The `grafana_api.api` submodule needs to be explicitly included in `setup.py` in order for it to be included in the package. I've gone ahead and created a PR which I believe addressed this: https://github.com/m0nhawk/grafana_api/pull/4.

**Comment by m0nhawk** [comment]
I appreciate the help. Already merged.

**Comment by svet-b** [comment]
Thanks @m0nhawk! I can see you're in the midst of a refactoring of the code - at least the previous way of calling the library functions doesn't appear to work any more, in v0.3.2. Do let me know when that's done so we can give it another go (and if necessary adapt our code to the new version). In the meantime we'll stick with the older version.

**Comment by m0nhawk** [comment]
@svet-b Yes, I'm currently rewritting the library with more concise API for running with helpers to create necessary JSON for request body.

Stick to the old version, in the next few weeks I will release more stable version including tests.
