### ISSUE TITLE
The installation via pip seems to be broken

### ISSUE THREAD

**Issue by sudhirpandey** [m0nhawk/grafana_api#56]
**Describe the bug**
 pip install -U grafana_api
Collecting grafana_api
  Downloading grafana_api-1.0.0.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/vagrant/testenvironment/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sszj54t9/grafana-api/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sszj54t9/grafana-api/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-sszj54t9/grafana-api/pip-egg-info
         cwd: /tmp/pip-install-sszj54t9/grafana-api/
    Complete output (19 lines):
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "/tmp/pip-install-sszj54t9/grafana-api/setup.py", line 8, in get_version
        ["git", "describe", "--tags", "--abbrev=0", "--match=[0-9]*"]
      File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib64/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--abbrev=0', '--match=[0-9]*']' returned non-zero exit status 128.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sszj54t9/grafana-api/setup.py", line 24, in <module>
        version=get_version(),
      File "/tmp/pip-install-sszj54t9/grafana-api/setup.py", line 13, in get_version
        "The version number cannot be extracted from git tag in this source "
    RuntimeError: The version number cannot be extracted from git tag in this source distribution; please either download the source from PyPI, or check out from GitHub and make sure that the git CLI is available.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**To Reproduce**
 pip install -U grafana_api

**Expected behavior**
should have been installed

- `grafana_api`: [ 1.0.0]

**Comment by m0nhawk** [comment]
This should be fixed now, there was no Python 3 wheels published.
