### ISSUE TITLE
Not able to establish Connection using pip lib grafana_api

### ISSUE THREAD

**Issue by superbhat** [m0nhawk/grafana_api#61]
**Describe the bug**
Hi ,
I have installed the pip install grafana_api, my aim is to retrieve the data from a particular datasource.
I did this 
Step 1 : pip3 install  grafana_api
Step 2: grafana_api = GrafanaFace(auth=api_key,host='https://XXX/api/datasources')
             OR
            grafana_api = GrafanaFace(auth=('user_name', pwd), host='https://XXX/api/datasources')
Step 3: **Commands works fine but when i do this** 
              grafana_api.datasource.get_datasource_by_id("14")
              or grafana_api.datasource.get_datasource_by_id(14)
it fails with below error
**
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //XXX/api/datasources/api/datasources/14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b2ece50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
**

Same works when i'm using request.get on same creds. i.e user name and pwd.

Do, let me know if anything else needed
Thanks
Suprabhat
**Additional context**

**Comment by amotl** [comment]
Dear Suprabhat,

you should probably pass a hostname to the `host` parameter, not the full URL. The parameter to designate a path prefix is called `url_path_prefix`.

With kind regards,
Andreas.

**Comment by superbhat** [comment]
@amotl Mate, it works, thanks. 
Now if u really can help me with this : I need to pull the data for all the datasources which thanks to u i can get using list_datasources(), if u can help to get the data part which get published on the dashboards for dfii datasources. Do we have got any function for that mate? 
Thanks in advance.

**Comment by amotl** [comment]
Dear @superbhat,

for pulling the data through Grafana, you might want to inspect the requests within the developer tools of your Browser.

With kind regards,
Andreas.

**Comment by superbhat** [comment]
Thanks pal. Will do closing the issue. Cheers. @amotl
